title: Chloe's Tech Journey
name: "Chloe's Tech Journey"
author: Chloe Nguyen
baseurl: ""
description: Summarize my learning journey
profile_url: "https://thuytrinhnguyen.github.io"

# Build settings
markdown: kramdown
highlighter: rouge
excerpt_separator: <!--more-->
plugins:
  - jekyll-feed
  - jekyll-archives
exclude:
  - Gemfile
  - Gemfile.lock
  - serve.sh
  - serve.bat
kramdown:
  input: GFM
  auto_ids: true
  syntax_highlighter: rouge
